# Generated by Django 3.2.13 on 2022-11-19 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='image',
            field=models.FileField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='qna',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
