# Generated by Django 3.2.13 on 2022-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
