# Generated by Django 3.2.13 on 2022-11-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('community', '0002_remove_qna_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
