# Generated by Django 3.2.13 on 2022-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_qna_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
