# Generated by Django 3.2.13 on 2022-11-22 01:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_qna_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/'),
        ),
    ]
