# Generated by Django 3.2.13 on 2022-11-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('W', '여성')], default='M', max_length=1, verbose_name='성별'),
        ),
    ]
