# Generated by Django 3.2.13 on 2022-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
