# Generated by Django 3.2.13 on 2022-11-17 01:24

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=20)),
                ('order_name', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR', unique=True)),
                ('order_request', multiselectfield.db.fields.MultiSelectField(choices=[('부재 시 경비실에 맡겨주세요', '부재 시 경비실에 맡겨주세요'), ('부재 시 택배함에 넣어주세요', '부재 시 택배함에 넣어주세요'), ('부재 시 집 앞에 놔주세요', '부재 시 집 앞에 놔주세요'), ('배송 전 연락 바랍니다', '배송 전 연락 바랍니다'), ('파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.', '파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.')], max_length=91)),
            ],
        ),
    ]
