# Generated by Django 3.2.13 on 2022-11-18 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=20)),
                ('order_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(null=True)),
                ('order_request', models.CharField(choices=[('부재 시 경비실에 맡겨주세요', '부재 시 경비실에 맡겨주세요'), ('부재 시 택배함에 넣어주세요', '부재 시 택배함에 넣어주세요'), ('부재 시 집 앞에 놔주세요', '부재 시 집 앞에 놔주세요'), ('배송 전 연락 바랍니다', '배송 전 연락 바랍니다'), ('파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.', '파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.')], max_length=50)),
                ('product', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('location_zipcode', models.CharField(max_length=20)),
                ('location_address', models.CharField(max_length=50)),
                ('location_detail', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=20)),
                ('order_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(null=True)),
                ('order_request', models.CharField(choices=[('부재 시 경비실에 맡겨주세요', '부재 시 경비실에 맡겨주세요'), ('부재 시 택배함에 넣어주세요', '부재 시 택배함에 넣어주세요'), ('부재 시 집 앞에 놔주세요', '부재 시 집 앞에 놔주세요'), ('배송 전 연락 바랍니다', '배송 전 연락 바랍니다'), ('파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.', '파손의 위험이 있는 상품입니다. 배송 시 주의해 주세요.')], max_length=50)),
                ('location_zipcode', models.CharField(max_length=20)),
                ('location_address', models.CharField(max_length=50)),
                ('location_detail', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
