# Generated by Django 3.2.13 on 2022-11-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='orderlistfinal',
            name='location',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='location_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='location_detail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='location_zipcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlistfinal',
            name='location_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlistfinal',
            name='location_detail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlistfinal',
            name='location_zipcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
