# Generated by Django 3.2.13 on 2022-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
