# Generated by Django 3.2.13 on 2022-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0002_alter_orderlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
