# Generated by Django 3.2.13 on 2022-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0003_auto_20221120_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistfinal',
            name='product_pk',
            field=models.IntegerField(null=True),
        ),
    ]
