# Generated by Django 3.2.13 on 2022-11-16 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('캐주얼룩', '캐주얼룩'), ('데이트룩', '데이트룩'), ('포멀룩', '포멀룩'), ('스트릿룩', '스트릿룩'), ('걸리쉬룩', '걸리쉬룩')], max_length=23)),
                ('like_users', models.ManyToManyField(related_name='like_style', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50, verbose_name='댓글내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='삭제여부')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='style.style', verbose_name='style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
            ],
            options={
                'verbose_name': '스타일 댓글',
                'verbose_name_plural': '스타일 댓글',
                'db_table': '스타일 댓글',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='style.style')),
            ],
        ),
    ]
