# Generated by Django 3.2.13 on 2022-11-15 13:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("style", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="style_review",
            options={"verbose_name": "스타일 댓글", "verbose_name_plural": "스타일 댓글"},
        ),
        migrations.RemoveField(
            model_name="style_review",
            name="grade",
        ),
        migrations.AddField(
            model_name="style_review",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="삭제여부",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="style_review",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AlterField(
            model_name="style_review",
            name="content",
            field=models.TextField(max_length=50, verbose_name="댓글내용"),
        ),
        migrations.AlterField(
            model_name="style_review",
            name="style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="style.style",
                verbose_name="style",
            ),
        ),
        migrations.AlterField(
            model_name="style_review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="댓글 작성자",
            ),
        ),
        migrations.AlterModelTable(
            name="style_review",
            table="스타일 댓글",
        ),
    ]
