# Generated by Django 3.2.13 on 2022-11-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_style_created_at'),
        ('style', '0002_style_hits'),
    ]

    operations = [
    ]
