# Generated by Django 3.2.13 on 2022-11-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='review',
            new_name='style',
        ),
    ]
