# Generated by Django 3.2.13 on 2022-11-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_merge_0002_style_created_at_0002_style_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='orderlists',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
