# Generated by Django 3.2.13 on 2022-11-15 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='save_users',
            field=models.ManyToManyField(related_name='save_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
