# Generated by Django 3.2.13 on 2022-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
    ]
