# Generated by Django 3.2.13 on 2022-11-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_count',
            field=models.IntegerField(default=1),
        ),
    ]
