# Generated by Django 3.2.13 on 2022-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
    ]
