# Generated by Django 3.2.13 on 2022-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_percent',
            field=models.IntegerField(null=True),
        ),
    ]
