# Generated by Django 3.2.13 on 2022-11-21 09:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('화이트', '화이트'), ('블랙', '블랙'), ('베이지', '베이지'), ('카키', '카키'), ('차콜', '차콜'), ('그레이', '그레이'), ('그린', '그린'), ('레드', '레드'), ('핫핑크', '핫핑크'), ('퍼플', '퍼플'), ('블루', '블루'), ('크림', '크림'), ('라이트퍼플', '라이트퍼플')], max_length=45),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('220', '220'), ('230', '230'), ('240', '240'), ('250', '250'), ('260', '260'), ('270', '270'), ('280', '280'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'FREE')], max_length=48),
        ),
    ]
