# Generated by Django 3.2.13 on 2022-11-21 16:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221121_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('220', 220), ('230', 230), ('240', 240), ('250', 250), ('260', 260), ('270', 270), ('280', 280), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'FREE')], max_length=48),
        ),
    ]
