# Generated by Django 3.2.13 on 2022-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost_2',
            field=models.IntegerField(null=True),
        ),
    ]
